<a href="https://colab.research.google.com/github/Nusrahkhan/Sariahhhhh/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PYTHON

## VARIABLES AND DATATYPES

In [ ]:
a = 10

In [ ]:
b= 12.5

In [ ]:
# FINDING TYPE
print(type(b))

<class 'float'>


## OPERATORS

In [ ]:
c = a

In [ ]:
# IDENTITY OPERATOR
print(c is a)

True


In [ ]:
n = 'build - week'

In [ ]:
b = 'build -  week'

In [ ]:
print(n is b)

False


## INPUT

In [ ]:
name = input("Enter your name: ")
print(name)

Enter your name: nusrah
nusrah


In [ ]:
type(name)

str

In [ ]:
# TYPE CASTING
a  = 12.33
b = int(a)
print(type(b))

<class 'int'>


In [ ]:
number = int(input("Enter a number: "))
print(number)

Enter a number: 12
12


In [ ]:
print(type(number))

<class 'int'>


## OUTPUT(PRINT STATEMENTS)

In [ ]:
# method 1
print("HEllo", name)
# method 2
# Only Strings can be concatenated
print("hello " + name)
# method 3
print(f"hello {name} and the number is {number}")

HEllo nusrah
hello nusrah
hello nusrah and the number is 12


## LOOPS

In [ ]:
# for loop
for gdg in range (10):
  print(gdg)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# while loop

i = 0
while(i < 5):
  print(i)
  i = i + 1

0
1
2
3
4


## STRINGS

In [ ]:
event = "0123456789"

In [ ]:
event[1:4]

'123'

In [ ]:
event[: 7]

'0123456'

In [ ]:
event[3:]

'3456789'

In [ ]:
# complete string will be printed
event[:]

'0123456789'

In [ ]:
event = 'build week'

In [ ]:
event.lower()

'build week'

In [ ]:
event = '          build week            '

In [ ]:
# removes unnecessary space in a string
event.strip()

'build week'

## LISTS

In [ ]:
list1 = ["gdg", 1, True]

In [ ]:
# ADDS NEW ELEMENT AT THE END
list1.append(False)

In [ ]:
list1

['breakthrough', 1, True, False]

In [ ]:
# INSERTS ELEMENTS AT THE SPECIFIED INDEX
list1.insert(0, 'breakthrough')

In [ ]:
list1

['breakthrough', 'breakthrough', 1, True, False]

In [ ]:
# DELETES THE ELEMENT SPECIFIED
list1.remove(False)

In [ ]:
list1

['breakthrough', 'breakthrough', 1, True]

In [ ]:
# DELETES THE ELEMENT AT SPECIFIED INDEX
list1.pop(1)

'breakthrough'

In [ ]:
list1

['breakthrough', 1, True]

## FUNCTIONS

In [ ]:
def adding(a, b):
  print("hello")
  return a+b

c = adding(3.55,4.50)
print(c)

hello
8.05


## CLASSES AND OBJECTS

In [ ]:
# PARENT CLASS
class Pet():
  # CONSTRUCTOR(ALWAYS EXECUTED WHEN OBJECT CREATED)
  def __init__(self, name, age, species):
    self.name = name
    self.age = age
    self.species = species

  def display_info(self):
    print()
    print(f"Name: {self.name}")
    print(f"Age: {self.age}")
    print(f"Species: {self.species}")

# CHILD CLASS
class Dog(Pet):
  def __init__(self, name, age, breed, color):
    # SUPER() USED TO CALL PARENT CLASS METHODS
    super().__init__(name, age, 'Dog')
    self.breed = breed
    self.color = color

  def display_info(self):
    super().display_info()
    print(f"Breed: {self.breed}")
    print(f"Color: {self.color}")


# OBJECT OF CLASS PET
cat = Pet('oreo', '1.5 years', 'cat')
cat.display_info()

# OBJECT OF CLASS DOG
dog = Dog('Leo', '1 year', 'Siberian Husky', 'B n W')
dog.display_info()


Name: oreo
Age: 1.5 years
Species: cat

Name: Leo
Age: 1 year
Species: Dog
Breed: Siberian Husky
Color: B n W


# NUMPY

In [ ]:
import numpy as np

## CREATING NUMPY ARRAYS

In [ ]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
# MATRIX
arr2d = np.array([[1,2,3], [1,2,4]])
print(arr2d)

[[1 2 3]
 [1 2 4]]


In [ ]:
# ARRAY WITH ALL ZEROES
zero = np.zeros((2,2))
print(zero)

[[0. 0.]
 [0. 0.]]


In [ ]:
# ARRAY WITH ALL ONES
one = np.ones((3,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# CREATES IDENTITY MATRIX
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## PROPERTIES OF NUMPY ARRAYS

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# DIMENSION OF NUMPY ARRAY
print(identity.ndim)

2


In [ ]:
# NUMBER OF ROWS AND COLUMNS
print(arr2d.shape)

(2, 3)


In [ ]:
# DATATYPE OF VALUES IN NUMPY ARRAY
print(identity.dtype)

float64


In [ ]:
# NUMBER OF ELEMENTS IN A NUMPY ARRAY
print(arr.size)

4


In [ ]:
arr = np.array([[2,3,5,6,7],[4,5,5,6,7]])
print(arr)


[[2 3 5 6 7]
 [4 5 5 6 7]]


## SLICING

In [ ]:
# SLICING IS SELECTING A PART OF AN ARRAY
print(arr[1, 1: 3])

[5 5]


## ARRAY INDEXING

In [ ]:
# ACCESSING AN ELEMENT BY SPECIFYING THE INDEX
arr1d = np.array([1,2,3])
print(arr1d[-1])

3


In [ ]:
# ACCESSING AN ELEMENT IN 2D ARRAY
print(arr[0, 1])

3


## FILTERING

In [ ]:
even = np.array([1,2,3,4,5,6,7,8,9,10])

mask = even % 2 == 0

print(even[mask])

[ 2  4  6  8 10]


# PANDAS

In [ ]:
import pandas as pd

In [ ]:
# READS A CSV FILE INTO NOTEBOOK
df = pd.read_csv('IRIS.csv')

In [ ]:
# DISPLAYS INFORMATION OF DATASET
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
# PRINTS INITIAL 'n' ROWS
df.head(10)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [ ]:
# PRINTS "n" ROWS FROM THE LAST
df.tail(7)

sepal_length  sepal_width  petal_length  petal_width         species
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
# PRINTS A SPECIFIC ROW
df.iloc[2]

sepal_length            4.7
sepal_width             3.2
petal_length            1.3
petal_width             0.2
species         Iris-setosa
Name: 2, dtype: object

In [ ]:
# DROPS ROWS WITH NULL VALUES
df.dropna()

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# FILL NANS WITH SPECIFIED VALUE
df.fillna(0, inplace = False)

In [ ]:
# RENAMES A COLUMN NAME
df.rename(columns = {'species': 'flower name'})

sepal_length  sepal_width  petal_length  petal_width     flower name
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

# TENSORFLOW

In [ ]:
import tensorflow as tf

## CREATING TENSORS

In [ ]:
scalar = tf.constant(5.55)
print(scalar)

tf.Tensor(5.55, shape=(), dtype=float32)


In [ ]:
tensor = tf.constant([1,2,3])
print(tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
matrix = tf.constant([[1,2],[3,4]])
print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## DIFF BETWEEN VARIABLE AND CONSTANT TENSORS

In [ ]:
# CONSTANT TENSORS = IMMUTABLE
# VARIBALE TENSORS = MUTABLE
matrix1 = tf.constant([[1,2,3],[4,5,6]])
print(matrix1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# REPLACING AN ELEMENT IN A 'VARIABLE TENSOR'
matrix1[0, 0].assign(100)
print(matrix1)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## OTHER WAYS TO MAKE TENSORS

In [ ]:
# CREATES A TENSOR WITH ZERO ELEMENTS
zero = tf.zeros([2,3,4,5])
print(zero)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [ ]:
# SPECIFYING THE DATATYPE OF VALUES IN A TENSOR
matrix1 = tf.constant([2,3,4], dtype = 'float16')
print(matrix1)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float16)


## RESHAPING TENSORS

In [ ]:
arr = tf.Variable([[2,3,4], [4,5,6]])
print(arr)



<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [4, 5, 6]], dtype=int32)>


In [ ]:
tf.reshape(arr, shape = (3, 2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 4],
       [5, 6]], dtype=int32)>

## OPERATIONS

In [ ]:
a = tf.Variable([[2,3],[2,2]])
b = tf.Variable([[1,2], [2,2]])

print(a @ b) # MATRIX MULTIPLICATION
print(a * b) # MULTIPLYING ELEMENTS OF TWO MATRICES AT SAME INDEX


tf.Tensor(
[[ 8 10]
 [ 6  8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 6]
 [4 4]], shape=(2, 2), dtype=int32)


## TRANSPOSE

In [ ]:
tf.transpose(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 2]], dtype=int32)>

## MIN, MAX, SUM, MEAN

In [ ]:
arr = tf.Variable([1.2,2.4,3.3,4.3,5.5])

In [ ]:
tf.reduce_min(arr)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.reduce_max(arr)

<tf.Tensor: shape=(), dtype=float32, numpy=5.5>

In [ ]:
tf.reduce_mean(arr)

<tf.Tensor: shape=(), dtype=float32, numpy=3.3400001525878906>

In [ ]:
tf.reduce_sum(arr)

<tf.Tensor: shape=(), dtype=float32, numpy=16.700000762939453>