<a href="https://colab.research.google.com/github/Nusrahkhan/Sariahhhhh/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

## Creating arrays

In [4]:
np.__version__

'2.0.2'

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
arr_2d = np.array([[[1,3], [4,5]], [[1,2], [3, 4]]])
print(arr_2d)

[[[1 3]
  [4 5]]

 [[1 2]
  [3 4]]]


In [14]:
matrix = np.ones((2, 2))
print(matrix)

[[1. 1.]
 [1. 1.]]


In [16]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Properties of numpy arrays

In [ ]:
print(type(arr_2d))

<class 'numpy.ndarray'>


In [18]:
#Dimensions of the array
print(arr_2d.ndim)

3


In [ ]:
# Number of rows and columns
print(arr_2d.shape)

(2, 3)


In [ ]:
# datatype
print(arr_2d.dtype)

int64


In [ ]:
#size
print(arr_2d.size)

6


In [23]:
# transpose
dim2 = np.array([[1,2, 3, 44, 56], [3, 4, 34, 45, 22]])
t = dim2.T
print(dim2)
print(t)

[[ 1  2  3 44 56]
 [ 3  4 34 45 22]]
[[ 1  3]
 [ 2  4]
 [ 3 34]
 [44 45]
 [56 22]]


## Array slicing

In [26]:
# arrayname[start: end]
new_array = np.array([2, 3, 5, 7, 8, 9, 10, 13, 15])
print(new_array[1: 4])

# with step
print(new_array[1: 9: 2])

# 2d array slicing
arr_2d = np.array([[1, 2, 3, 5] ,[3, 5, 6, 4]])
print(arr_2d[1, 1: 4])

[3 5 7]
[ 3  7  9 13]
[5 6 4]


In [24]:
print(dim2[1, :3])

[ 3  4 34]


## Array indexing

In [27]:
# 2d array indexing
print(arr_2d[0, 1])

2


In [ ]:
# negative indexing
print(arr[-1])

10


In [30]:
# functions on numpy arrays
print(np.sqrt(arr_2d))
print(np.exp(arr_2d))

[[1.         1.41421356 1.73205081 2.23606798]
 [1.73205081 2.23606798 2.44948974 2.        ]]
[[  2.71828183   7.3890561   20.08553692 148.4131591 ]
 [ 20.08553692 148.4131591  403.42879349  54.59815003]]


## Filtering

In [ ]:
mask = arr % 2 == 0
print(arr[mask])

[ 2  4  6  8 10]
