<a href="https://colab.research.google.com/github/Nusrahkhan/Sariahhhhh/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## Creating arrays

In [ ]:
np.__version__

'2.0.2'

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr_2d = np.array([[[1,3], [4,5]], [[1,2], [3, 4]]])
print(arr_2d)

[[[1 3]
  [4 5]]

 [[1 2]
  [3 4]]]


In [ ]:
matrix = np.ones((2, 2))
print(matrix)

[[1. 1.]
 [1. 1.]]


In [ ]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Properties of numpy arrays

In [ ]:
print(type(arr_2d))

<class 'numpy.ndarray'>


In [ ]:
#Dimensions of the array
print(arr_2d.ndim)

3


In [ ]:
# Number of rows and columns
print(arr_2d.shape)

(2, 3)


In [ ]:
# datatype
print(arr_2d.dtype)

int64


In [ ]:
#size
print(arr_2d.size)

6


In [ ]:
# transpose
dim2 = np.array([[1,2, 3, 44, 56], [3, 4, 34, 45, 22]])
t = dim2.T
print(dim2)
print(t)

[[ 1  2  3 44 56]
 [ 3  4 34 45 22]]
[[ 1  3]
 [ 2  4]
 [ 3 34]
 [44 45]
 [56 22]]


## Array slicing

In [ ]:
# arrayname[start: end]
new_array = np.array([2, 3, 5, 7, 8, 9, 10, 13, 15])
print(new_array[1: 4])

# with step
print(new_array[1: 9: 2])

# 2d array slicing
arr_2d = np.array([[1, 2, 3, 5] ,[3, 5, 6, 4]])
print(arr_2d[1, 1: 4])

[3 5 7]
[ 3  7  9 13]
[5 6 4]


In [ ]:
print(dim2[1, :3])

[ 3  4 34]


## Array indexing

In [ ]:
# 2d array indexing
print(arr_2d[0, 1])

2


In [ ]:
# negative indexing
print(arr[-1])

10


In [ ]:
# functions on numpy arrays
print(np.sqrt(arr_2d))
print(np.exp(arr_2d))

[[1.         1.41421356 1.73205081 2.23606798]
 [1.73205081 2.23606798 2.44948974 2.        ]]
[[  2.71828183   7.3890561   20.08553692 148.4131591 ]
 [ 20.08553692 148.4131591  403.42879349  54.59815003]]


## Filtering

In [ ]:
mask = arr % 2 == 0
print(arr[mask])

[ 2  4  6  8 10]


# PANDAS

In [1]:
import pandas as pd

In [26]:
series = pd.Series(['gdg', 'gdg again', 'gdg once more'], index = ['a', 'b', 'c'])

In [27]:
print(series)

a              gdg
b        gdg again
c    gdg once more
dtype: object


In [3]:
df = pd.read_csv('IRIS.csv')

In [4]:
df.info()
# gives basic information about the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [11]:
df.head(10)
# gives the first 'n' rows from the top

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [10]:
# last 'n' rows
df.tail(10)

sepal_length  sepal_width  petal_length  petal_width         species
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [12]:
df.iloc[2]
# select a particular row

sepal_length            4.7
sepal_width             3.2
petal_length            1.3
petal_width             0.2
species         Iris-setosa
Name: 2, dtype: object

In [13]:
df.dropna()

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [16]:
df.fillna(0)

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [15]:
df.rename(columns = {"species": "name"})
# rename column name

sepal_length  sepal_width  petal_length  petal_width            name
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [28]:
df.isna().any()

sepal_length    False
sepal_width     False
petal_length    False
petal_width     False
species         False
dtype: bool