<a href="https://colab.research.google.com/github/Nusrahkhan/Sariahhhhh/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Creating arrays

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


## Properties of numpy arrays

In [4]:
print(type(arr_2d))

<class 'numpy.ndarray'>


In [5]:
#Dimensions of the array
print(arr_2d.ndim)

2


In [6]:
# Number of rows and columns
print(arr_2d.shape)

(2, 3)


In [7]:
# datatype
print(arr_2d.dtype)

int64


In [8]:
#size
print(arr_2d.size)

6


## Array slicing

In [9]:
# arrayname[start: end]
new_array = np.array([2, 3, 5, 7, 8, 9, 10, 13, 15])
print(new_array[1: 4])

# with step
print(new_array[1: 9: 2])

# 2d array slicing
arr_2d = np.array([[1, 2, 3, 5] ,[3, 5, 6, 4]])
print(arr_2d[1, 1: 4])

[3 5 7]
[ 3  7  9 13]
[5 6 4]


## Array indexing

In [10]:
# 2d array indexing
print(arr_2d[0, 2])

3


In [11]:
# negative indexing
print(arr[-1])

10


## Filtering

In [12]:
mask = arr % 2 == 0
print(arr[mask])

[ 2  4  6  8 10]
